# 文章页相关配置
post:
  math:
    enable: true  # 开启数学公式支持
    engine: mathjax # 使用 MathJax 引擎 (比 Katex 更强大，兼容性更好)
    specific: true # 建议开启：只有在文章开头写了 math: true 才加载脚本，提升网站速度

# 以下是可选的美化配置，你可以稍后调整
navbar:
  blog_title: "博客名字" # 导航栏左侧的标题
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
  
index:
  banner_img: /img/default.jpg # 首页大图
  slogan:
    enable: true

    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text: "测试首页显示的打字机文字" # 首页显示的打字机文字
  
favicon: /img/fluid.png

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /img/fluid.png

about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "about-name"
  intro: "about-intro"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, the icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
#    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }
