# 文章页相关配置
#post:
#  math:
#    enable: true  # 开启数学公式支持
#    engine: mathjax # 使用 MathJax 引擎 (比 Katex 更强大，兼容性更好)
#    mathjax:
#       设置输出选项
#      output:
#        font: 'mathjax-tex' # 这是最接近标准 LaTeX 的字体
#        displayOverflow: 'overflow' # 手机端过长公式允许左右滑动
#    specific: true # 建议开启：只有在文章开头写了 math: true 才加载脚本，提升网站速度
    
# 确保这里是唯一的 post 节点
post:
  math:
    enable: true
    engine: mathjax
    specific: true
    mathjax:
      # 1. 强制使用 MathJax 3 的“现代”字体，这最接近你图片里的效果
      output:
        font: 'mathjax-modern' 
        displayOverflow: 'overflow'
      # 2. 确保渲染器能识别并正确处理行间公式
      tex:
        inlineMath: [['$', '$'], ['\\(', '\\)']]
        displayMath: [['$$', '$$'], ['\\[', '\\]']]
        # 允许使用复杂的 LaTeX 扩展，渲染图片里的定义符号和花体
        packages: {'[+]': ['ams', 'base', 'configmacros']}

# 以下是可选的美化配置，你可以稍后调整
navbar:
  blog_title: "Maelstrom Portal" # 导航栏左侧的标题
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
  
index:
  banner_img: /img/default.jpg # 首页大图
  slogan:
    enable: true

    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text: "Just for fun" # 首页显示的打字机文字
  
favicon: /img/fluid.png

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /img/fluid.png

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3

  # 分类的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for categories, with a minus sign is reverse order
  # Options: length | name
  order_by: "-length"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  # Collapse depth. If 0, all posts collapsed. If greater than 0, it will be expanded by default if there are subcategories
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for posts, with a minus sign is reverse order
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
  # The maximum number of posts in a single category. If the limit is exceeded, it will be displayed More. If 0 no limit
  post_limit: 10


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "About me"
  intro: "关于我"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, the icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/phlzy", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
#    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }

